name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            libglfw3-dev \
            libgl1-mesa-dev \
            libx11-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxi-dev \
            libxrandr-dev

      - name: Build raylib
        run: |
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP
          sudo make install

      - name: Build game
        run: make

      - name: Package Linux build
        run: |
          mkdir release
          cp game release/
          tar -czf MyGame-Linux.tar.gz -C release .

      - name: Upload Linux package
        uses: actions/upload-artifact@v4
        with:
          name: MyGame-Linux
          path: MyGame-Linux.tar.gz


  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MSYS2 and raylib
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-raylib
            make
            git
            zip
      - name: Build raylib DLL
        shell: msys2 {0}
        run: |
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED
          cp raylib.dll /mingw64/bin/

      - name: Build game
        shell: msys2 {0}
        run: make

      -  name: Package Windows build
         shell: msys2 {0}
         run: |
          mkdir -p release
          cp game.exe release/
          cp /mingw64/bin/libraylib.dll release/
          cp /mingw64/bin/glfw3.dll release/
      
          cd release
          zip -r ../MyGame-Windows.zip .
      
      - name: Upload Windows package
        uses: actions/upload-artifact@v4
        with:
          name: MyGame-Windows
          path: MyGame-Windows.zip